version: '1.0.{build}'


notifications:
  - provider: Email
    to:
      - scrgiorgio@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
  
environment:

  PYPI_USERNAME: scrgiorgio
  PYPI_PASSWORD:
    secure: 6DHH80JPNRCtIYxWc/h88Q==
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      PYTHON_VERSION: 3.6
      PYTHON_DIR: "C:\\Python36-x64"          
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      PYTHON_VERSION: 3.7
      PYTHON_DIR: "C:\\Python37-x64" 
  
# 
#if you need to debug uncomment these lines (see https://www.appveyor.com/docs/how-to/rdp-to-build-worker/)
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - choco install -y --allow-empty-checksums swig 

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build 
  - cd build 
  - set PATH=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%PATH%
  - python -m pip install numpy setuptools wheel twine
  - cmake -G "%CMAKE_GENERATOR%" -DPYTHON_VERSION=%PYTHON_VERSION% -DPYTHON_EXECUTABLE=%PYTHON_DIR%/python.exe -DPYTHON_INCLUDE_DIR=%PYTHON_DIR%/include -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/build/install ../
  - cmake --build . --target ALL_BUILD   --config RelWithDebInfo
  - cmake --build . --target INSTALL     --config RelWithDebInfo   
  - cmake --build . --target dist        --config RelWithDebInfo

# test are already in cmake
test: off

# Deploy to PyPI if is a  tagged release 
on_success:
  - echo [distutils]                > %USERPROFILE%\\.pypirc
  - echo index-servers =           >> %USERPROFILE%\\.pypirc
  - echo     pypi                  >> %USERPROFILE%\\.pypirc
  - echo [pypi]                    >> %USERPROFILE%\\.pypirc
  - echo username=%PYPI_USERNAME%  >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD%  >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - set PATH=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%PATH% 
  - cd %APPVEYOR_BUILD_FOLDER%\build\install
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true") { Invoke-Expression "twine upload --skip-existing dist/*.whl" } Else { write-output "Not on a tag, won't deploy to pypi"}

